#Load bot token
"bot_token": YOUR_BOT_TOKEN
#Load bot token

TEAM:

  -

  - 

#Messages

commands: >

   My commands:

   /resources - Golem Network resources

   /videos - Golem Network related videos

   /events - Upcoming events

   /extras - Extra commands

extras: >

   /releases - Github releases page

   /adminlist - List the admins of @Golemproject

   /rules - Golem Network | GNT telegram channel rules

start: >

   Hi, start off with /commands

resources: >

   Golem Network resources:

   [Website](https://golem.network/)

   [Github](https://github.com/golemfactory)

   [Documentation](https://explorer.golem.network/documentation/understanding-beta/)

   [Blog](https://blog.golemproject.net/)

   [Twitter](https://twitter.com/golemproject)

   [Reddit](https://www.reddit.com/r/golemproject)

   [Chat](https://chat.golem.network/)

   [Download](https://explorer.golem.network/rendering/download/)

   [Whitepaper](https://explorer.golem.network/crowdfunding/Golemwhitepaper.pdf)

   [Trello Golem Comms Archive](https://trello.com/b/95eZBUfT/golem-comms-archive)

   [Latest AMA](https://www.reddit.com/r/GolemProject/comments/b11r0p/our_april_ama_is_happening_post_your_questions_we/)

   [Kenny's Golem Stats](https://kascheri12.github.io/dashboard/)

videos: >

   Golem Network videos/presentations:

   [Golem Network Youtube Channel](https://www.youtube.com/channel/UCl3fxgrSML2sL3UYZrynbMg)

   [Devcon4](https://youtu.be/w0bYO8DOT8A)

rules: >

   Golem Network | GNT telegram channel rules:

   [Rule #1, don't feed the trolls](https://t.me/GolemProject/26111)

   [Rule #1 of this group: NO MCAFFEE MENTIONS](https://t.me/GolemProject/25511)

   [Rule #1 is no attacking the team.](https://t.me/GolemProject/25630)

   [Stay hydrated people. Rule #1](https://t.me/GolemProject/38490)

adminlist: >

   Golem Network | GNT Admin List:

   Jasper - @jaspervv99

   MP - @mariapaulafn

releases: >

   [Golem Network Releases List](https://github.com/golemfactory/golem/releases)
